const SET_CONFIG_HOSTNAME = 'SET_CONFIG_HOSTNAME';
const SET_CONFIG_HARDWARE = 'SET_CONFIG_HARDWARE';
const SET_USERDATA = 'SET_USERDATA';

export {
    SET_CONFIG_HOSTNAME,
    SET_CONFIG_HARDWARE,
    SET_USERDATA
};
